spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.org.apache.http=DEBUG
#logging.level.httpclient.wire=DEBUG

server.port=8080

spring.datasource.driverClassName=org.postgresql.Driver
SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm